# Generated by Django 4.0.5 on 2022-07-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('descricao', models.TextField()),
                ('duracao', models.DurationField()),
                ('video_url', models.URLField(max_length=512)),
            ],
        ),
    ]
